theme: jekyll-theme-primer

title: Apprendre Ã  programmer
# description: Contenus pour le cours Â«â€¯Apprendre Ã  programmerâ€¯Â», L3 SDL parcours LCN, universitÃ© Paris Nanterre
emojicon: ğŸ

url: "https://loicgrobol.github.io/"
baseurl: "/apprendre-programmer/"
repository: "loicgrobol/apprendre-programmer"
environ_repository: "loicgrobol/apprendre-programmer-environ"
repo_branch: "main"

exclude:
  - "*.py.md"
  - "**/local"

include:
  - _pages
  - "*.py.html"
  - "pdf_slides/*"

