title = "Apprendre Ã  programmer"
description = "Contenus pour le cours Â«â€¯Apprendre Ã  programmerâ€¯Â», L3 SDL, UniversitÃ© Paris Nanterre"
emojicon = "ğŸ"

url = "https://loicgrobol.github.io"
baseurl = "/apprendre-programmer"
repository = "loicgrobol/apprendre-programmer"
repo_branch = "main"
